#!/bin/bash

source bash_helpers.sh


usage()
{
    echo "Usage: proot_is_running [proot name] [-q]"
    echo ""
    echo "Checks if the given proot is accesible."
    echo "If no proot name is given, the loaded proot env will be used."
    echo "We basically check if the proot's screen is running."
    echo ""
}




if [[ "$TERMUX_VERSION" == "" ]];
then
    abort "This script is intended for Termux only."
fi


if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]];
then
    usage
    abort
fi


if ! [[ -v PROOT_NAME ]];
then
    PROOT_NAME=$1
fi


if [[ "$1" == "-q" ]] || [[ "$2" == "-q" ]];
then
    QUIET=1
fi


proot_exists $PROOT_NAME -q


if [[ "$?" == "0" ]];
then
    screen -list | grep -q "proot_${PROOT_NAME}"

    if [[ "$?" == "0" ]];
    then
        if ! [[ -v QUIET ]];
        then
            echo "The proot '$PROOT_NAME' is running."
            echo ""
        fi

        exit 0
    else
        if ! [[ -v QUIET ]];
        then
            echo "The proot '$PROOT_NAME' isn't running."
            echo ""
        fi

        exit 1
    fi
fi
