#!/bin/bash

source bash_helpers.sh

if ! [[ -v BASH_HELPERS_LOADED ]];
then
    echo -e "BASH helpers not found in PATH. Install it first.\n"
    exit 1
fi


usage()
{
    echo "Usage: penter_admin [proot name]"
    echo ""
    echo "Enters into the given proot installation as root."
    echo "If a proot env is loaded, its config will be used."
    echo ""
}




if [[ "$TERMUX_VERSION" == "" ]];
then
    abort "This script is intended for Termux only."
fi


if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]];
then
    usage
    abort
fi


if ! [[ -v PROOT_NAME ]];
then
    PROOT_NAME=$1
fi


proot_exists $PROOT_NAME -q

if [[ "$?" == "0" ]];
then
    if ! [ "$EXT_SD" == "" ];
    then
        SD_BINDING="--bind $EXT_SD:/mnt/extsd"
    fi

    TERMUX_HOME_BINDING="--bind $HOME:/mnt/termux_home"

    PROOT_LOGIN_OPTS="$PROOT_NAME "
    PROOT_LOGIN_OPTS+="$SD_BINDING "
    PROOT_LOGIN_OPTS+="$TERMUX_HOME_BINDING "
    PROOT_LOGIN_OPTS+="--shared-tmp "
    PROOT_LOGIN_OPTS+="$PROOT_LOGIN_EXTRA_OPTS"

    proot-distro login $PROOT_LOGIN_OPTS
fi

