#!/bin/bash

source bash_helpers.sh

if ! [[ -v BASH_HELPERS_LOADED ]];
then
    echo -e "BASH helpers not found in PATH. Install it first.\n"
    exit 1
fi


usage()
{
    echo "Usage: pexec_admin <proot name> <command line>"
    echo ""
    echo "Executes the given command line in the given proot installation."
    echo "The command line is executed as root."
    echo ""
    echo "If a proot env is loaded, its config will be used."
    echo ""
}




if [[ "$TERMUX_VERSION" == "" ]];
then
    abort "This script is intended for Termux only."
fi


if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]];
then
    usage
    abort
fi


if [[ -v PROOT_NAME ]];
then
    CMDLINE=$*
else
    PROOT_NAME=$1
    CMDLINE=${@:2}
fi


if ! [[ "$EXT_SD" == "" ]];
then
    SD_BINDING="--bind $EXT_SD:/mnt/extsd"
fi


proot_exists $PROOT_NAME -q


if [[ "$?" == "0" ]];
then
    PROOT_LOGIN_OPTS="$PROOT_NAME "
    PROOT_LOGIN_OPTS+="$SD_BINDING "
    PROOT_LOGIN_OPTS+="--shared-tmp "
    PROOT_LOGIN_OPTS+="$PROOT_LOGIN_EXTRA_OPTS "
    PROOT_LOGIN_OPTS+="-- $CMDLINE"
    
    proot-distro login $PROOT_LOGIN_OPTS
fi

