#!/bin/bash

source bash_helpers.sh

if ! [[ -v BASH_HELPERS_LOADED ]];
then
    echo -e "BASH helpers not found in PATH. Install it first.\n"
    exit 1
fi


usage()
{
    echo "Usage: proot_exists <proot name> [-q]"
    echo "If -q is provided, no message Will be printed."
    echo ""
}




if [[ "$TERMUX_VERSION" == "" ]];
then
    abort "This script is intended for Termux only."
fi


if [[ "$1" == "" ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]];
then
    usage
    abort
fi


PROOT_NAME=$1

if [[ "$2" == "-q" ]];
then
    QUIET=1
fi


if [[ "$PROOT_NAME" == "" ]] || ! [[ -d "$PROOTS/$PROOT_NAME" ]];
then
    if ! [[ -v QUIET ]];
    then
        echo "No proot named '$PROOT_NAME' exists."
        echo ""
    fi

    exit 1
    
else
    if ! [[ -v QUIET ]];
    then
        echo "The proot '$PROOT_NAME' exists."
        echo ""
    fi

    exit 0
fi
