#!/bin/bash

source bash_helpers.sh

if ! [[ -v BASH_HELPERS_LOADED ]];
then
    echo -e "BASH helpers not found in PATH. Install it first.\n"
    exit 1
fi


usage()
{
    echo "Usage: stop_proot [proot name]"
    echo ""
    echo "If a proot env is loaded, its name will be used."
    echo ""
}




if [[ "$TERMUX_VERSION" == "" ]];
then
    abort "This script is intended for Termux only."
fi


if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]];
then
    usage
    abort
fi


if ! [[ -v PROOT_NAME ]];
then
    PROOT_NAME=$1
fi


proot_exists $PROOT_NAME -q


if [[ "$?" == "0" ]];
then
    is_proot_running $PROOT_NAME

    if ! [[ "$?" == "0" ]];
    then
        abort "The proot '$PROOT_NAME' is already off."
    fi


    echo "Trying to stop proot ..."

    pexec_admin $PROOT_NAME stop_sshd

    if ! [[ "$?" == "0" ]];
    then
        abort "Command line returned non-zero. Something failed."
    fi

    echo "Proot '$PROOT_NAME' should be closed now."
    echo ""
fi

