#!/bin/bash

source bash_helpers.sh

if ! [[ -v BASH_HELPERS_LOADED ]];
then
    echo -e "BASH helpers not found in PATH. Install it first.\n"
    exit 1
fi


if [[ "$TERMUX_VERSION" == "" ]];
then
    abort "This script is only for Termux."
fi


echo ""
echo "Searching for external SD card..."
echo "---------------------------------"

if ! [[ -d "$HOME/storage" ]];
then
    echo ""
    echo "Can't access Android filesystem."
    echo "Execute 'termux-setup-storage' first, to grant Termux permission."
    echo ""
    echo "It is also recommended, if you have not done it yet,"
    echo "to execute 'termux-change-repo' for selecting a mirror"
    echo "for downloading the packages, although is not strictly necesary."
    echo ""

    abort
fi


if ! [[ -d "$HOME/storage/external-1" ]];
then
    echo ""
    echo "No external SD card detected."
    echo "If you have recently replaced the SD card,"
    echo "please run termux-setup-storage again."
    echo ""

else
    extsd_path=$(realpath "$HOME/storage/external-1")
    extsd_id=${extsd_path:9:9}
    echo $extsd_id > "$HOME/.extsd_id"
    
    EXTSD_PATH="/storage/${extsd_id}"
    EXTSD_LINK="$HOME/storage/extsd"

    if [[ -f "$EXTSD_LINK" ]];
    then
        rm "$EXTSD_LINK"
    fi

    ln -s "$EXTSD_PATH" "$EXTSD_LINK"

    echo ""
    echo "Added ~/.extsd_id file with the SD card ID."
    echo "Also, an ~/storage/extsd symlink has been created."
    echo ""
    echo "Remember that the ~/storage/external-1 one points to"
    echo "Termux folder in the external sdcard, not to the"
    echo "external sd card root."
    echo ""
fi
