#!/bin/bash

source bash_helpers.sh


if [[ "$TERMUX_VERSION" == "" ]];
then
    abort "This script is intended for Termux only."
fi


if [[ -f "$HOME/.3d_accel_setup_done" ]];
then
    abort "3D acceleration setup already done."
fi


PACKAGES="mesa-zink virglrenderer-mesa-zink "
PACKAGES+="virglrenderer-android vulkan-loader-android"


pkg install $PACKAGES -y


echo "Done."
echo ""

touch "$HOME/.3d_accel_setup_done"
