#!/bin/bash

source bash_helpers.sh


if [[ "$TERMUX_VERSION" == "" ]];
then
    abort "This script is intended for Termux only."
fi


if [[ -f "$HOME/.x11_setup_done" ]];
then
    abort "X11 setup already done."
fi


echo "Refreshing package database..."
echo "------------------------------"

pkg update


if ! [[ -f "$PREFIX/etc/apt/sources.list.d/tur.list" ]];
then
    echo "Installing Termux User Repository ..."
    echo "-------------------------------------"
    
    pkg install tur-repo -y
fi


if ! [[ -f "$PREFIX/etc/apt/sources.list.d/x11.list" ]];
then
    echo "Installing X11 repository ..."
    echo "-----------------------------"

    pkg install x11-repo -y
fi


if ! [[ -f "$PREFIX/bin/termux-x11" ]];
then
    echo "Installing Termux X11 server..."
    echo "-------------------------------"

    pkg install termux-x11-nightly -y
fi


if ! [[ -f "$PREFIX/bin/pulseaudio" ]];
then
    echo "Installing Pulseaudio server..."
    echo "-------------------------------"

    pkg install pulseaudio -y
fi
