#!/bin/bash

source bash_helpers.sh


usage()
{
    echo "Usage: penter_admin [proot name]"
    echo ""
    echo "Enters into the given proot installation as root."
    echo "If a proot env is loaded, its config will be used."
    echo ""
}




if [[ "$TERMUX_VERSION" == "" ]];
then
    abort "This script is intended for Termux only."
fi


if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]];
then
    usage
    abort
fi


if ! [[ -v PROOT_NAME ]];
then
    PROOT_NAME=$1
fi


proot_exists $PROOT_NAME

if [[ "$?" == "0" ]];
then
    if ! [ "$EXT_SD" == "" ];
    then
        SD_BINDING="--bind $EXT_SD:/mnt/extsd"
    fi

    proot-distro login $PROOT_NAME $SD_BINDING --shared-tmp
fi

