#!/bin/bash

source bash_helpers.sh


usage()
{
    echo "Usage: penter [proot name] <username>"
    echo ""
    echo "Enters into the given proot installation as the given username."
    echo "If a proot env is loaded, its name will be used, but you must"
    echo "provide at least the username to login with."
    echo ""
}


if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]];
then
    usage
    abort
fi


if ! [[ "$1" == "" ]] && ! [[ "$2" == "" ]];
then
    PROOT_NAME=$1
    PROOT_USER=$2

elif [[ -v PROOT_NAME ]] && ! [[ "$1" == "" ]];
then
    PROOT_USER=$1

else
    usage
    abort
fi


proot_exists $PROOT_NAME

if [[ "$?" == "0" ]];
then
    if ! [[ "$EXT_SD" == "" ]];
    then
        SD_BINDING="--bind $EXT_SD:/mnt/extsd"
    fi

    proot-distro login $PROOT_NAME --user $PROOT_USER $SD_BINDING --shared-tmp
fi

