#!/bin/bash

source bash_helpers.sh


usage()
{
    echo "Usage: pexec_admin <proot name> <command line>"
    echo ""
    echo "Executes the given command line in the given proot installation."
    echo "The command line is executed as root."
    echo ""
    echo "If a proot env is loaded, its config will be used."
    echo ""
}




if [[ "$TERMUX_VERSION" == "" ]];
then
    abort "This script is intended for Termux only."
fi


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi


if [[ -v PROOT_NAME ]];
then
    CMDLINE=$*
else
    PROOT_NAME=$1
    CMDLINE=${@:2]
fi


if ! [[ "$EXT_SD" == "" ]];
then
    SD_BINDING="--bind $EXT_SD:/mnt/extsd"
fi


proot_exists $PROOT_NAME


if [[ "$?" == "0" ]];
then
    proot-distro login $PROOT_NAME $SD_BINDING --shared-tmp -- $CMDLINE
fi

