#!/bin/bash

source bash_helpers.sh


usage()
{
    echo "Usage: proot_exists <proot name> [-q]"
    echo "If -q is provided, no message Will be printed."
    echo ""
}




if [[ "$TERMUX_VERSION" == "" ]];
then
    abort "This script is intended for Termux only."
fi


PROOT_NAME=$1

if [[ "$2" == "-q" ]];
then
    QUIET=1
fi

if [[ "$PROOT_NAME" == "" ]] || ! [[ -d "$PROOTS/$PROOT_NAME" ]];
then
    if ! [[ -v QUIET ]];
    then
        echo "No proot named '$PROOT_NAME' exists."
        echo ""
    fi

    exit 1
    
else
    if ! [[ -v QUIET ]];
    then
        echo "The proot '$PROOT_NAME' exists."
        echo ""
    fi

    exit 0
fi
