#!/bin/bash

source bash_helpers.sh


usage()
{
    echo "Usage: start_proot [proot name]"
    echo ""
    echo "If a proot env is loaded, its name will be used."
    echo ""
    echo "The pexec commands allows executing command lines in proot"
    echo "but, after execution, the proot session is closed."
    echo ""
    echo "This script starts the proot SSH server (listening in the 8002"
    echo "port) and keeps the session opened until the server is killed."
    echo ""
    echo "This way you can connect to proot from SSH and execute all"
    echo "command lines you like."
    echo ""
    echo "The proot will be shutdown after executing 'stop_proot' or when"
    echo "Termux is closed."
    echo ""
}




if [[ "$TERMUX_VERSION" == "" ]];
then
    abort "This script is intended for Termux only."
fi


if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]];
then
    usage
    abort
fi


if ! [[ -v PROOT_NAME ]];
then
    PROOT_NAME=$1
fi


proot_exists $PROOT_NAME -q

if [[ "$?" == "0" ]];
then
    is_proot_running $PROOT_NAME
    
    
    if [[ "$?" == "0" ]];
    then
        abort "The proot '$PROOT_NAME' is already running."
    fi
    
    
    if ! [[ "$EXT_SD" == "" ]];
    then
        SD_BINDING="--bind $EXT_SD:/mnt/extsd"
    fi


    CMDLINE="/usr/sbin/sshd -p 8002"


    PROOT_CMDLINE="proot-distro login "
    PROOT_CMDLINE+="$PROOT_NAME $SD_BINDING "
    PROOT_CMDLINE+="--shared=tmp --no-kill-on-exit -- $CMDLINE"
    
    
    echo "Trying to power-on proot '$PROOT_NAME ..."
    screen -dmS proot_${PROOT_NAME} $PROOT_CMDLINE
    
    is_proot_running $PROOT_NAME
    
    if [[ "$?" == "0" ]];
    then
        echo "Proot '${PROOT}' should be now available for remote working."
        echo ""
    
    else
        abort "Can't find proot's screen. Something failed."
    fi
fi

