#!/bin/bash

source bash_helpers.sh


usage()
{
    echo "Usage: stop_proot [proot name]"
    echo ""
    echo "If no proot name is given, you must load a proot environment file."
    echo ""
}




if [[ "$TERMUX_VERSION" == "" ]];
then
    abort "This script is intended for Termux only."
fi


if [[ "$1" == "" ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]];
then
    usage
    abort
fi


if ! [[ -v PROOT_NAME ]];
then
    PROOT_NAME=$1
fi


if [[ "$PROOT_NAME" == "" ]];
then
    usage
    abort
fi


if ! [[ -v PROOT_PATH ]];
then
    PROOT_PATH="$PROOTS/$PROOT_NAME"
fi


if ! [[ -d "$PROOT_PATH" ]];
then
    abort "The proot '$PROOT_NAME' does not exist."
fi


is_proot_running $PROOT_NAME

if ! [[ "$?" == "0" ]];
then
    abort "The proot '$PROOT_NAME' is already off."
fi


echo "Trying to stop proot ..."

pexec_admin $PROOT_NAME stop_sshd

if ! [[ "$?" == "0" ]];
then
    abort "Command line returned non-zero. Something failed."
fi


echo "Proot '$PROOT_NAME' should be closed now."
echo ""

